#!/bin/bash



if [ "$1" == "" ]; then
   echo "sort-categories INFILE"
   exit 1
fi

if [ ! -e "$1" ]; then
   echo "Input file does not exist."
   exit 1
fi
INFILE="$1"



i=0
while read -r URL; do

   FILENAME=${URL##*/}
#   echo "16/$INFILE/$(printf "%03u" $i)-$FILENAME"
   mv -v "16/$INFILE/$FILENAME" "16/$INFILE/$(printf "%03u" $i)-$FILENAME"
   mv -v "32/$INFILE/$FILENAME" "32/$INFILE/$(printf "%03u" $i)-$FILENAME"
   mv -v "64/$INFILE/$FILENAME" "64/$INFILE/$(printf "%03u" $i)-$FILENAME"
   mv -v "128/$INFILE/$FILENAME" "128/$INFILE/$(printf "%03u" $i)-$FILENAME"
   ((i++))

done < "$INFILE"



